name: Good First Issue Template
description: Create a Good First Issue for new contributors (C++)
title: "[Good First Issue]: "
labels: ["Good First Issue"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort. If this is your first open-source contribution, welcome!

        This template is designed to help you create a **Good First Issue (GFI)** —
        a small, well-scoped task that helps new contributors learn the
        **Hiero C++ SDK** codebase and workflow.

        ---

  - type: textarea
    id: intro
    attributes:
      label: 🆕🐥 First Timers Only
      description: Who is this issue for?
      value: |
        This issue is intended for people who have never contributed or have made
        minimal contributions to the **Hiero C++ SDK**.

        We know that opening a pull request (PR) can be a major barrier for new contributors.
        The goal of this issue—and all other **Good First Issues**—is to help you make
        your first contribution in a safe and guided way.

        No prior knowledge of Hiero, Hedera, or distributed ledger technology is required.
        Basic familiarity with C++ and Git is sufficient.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 📋 Good First Issue (GFI) Guidelines
        >
        > A Good First Issue must have a **narrow scope** and **fully specified instructions**.
        >
        > **Examples of acceptable GFI work include:**
        >
        > - **Very small, explicitly defined changes to `src` code**
        >   *(mechanical only — no behavior or API changes)*, such as:
        >   - Extracting helper methods
        >   - Improving naming or readability
        >   - Adding `const` correctness when explicitly specified
        > - **Refactors of existing examples**
        >   - Splitting large `main()` functions into helpers
        >   - Reorganizing code without changing behavior
        > - **Documentation improvements**
        >   - Improving Doxygen comments
        >   - Fixing known typos or unclear wording
        > - **Small, clearly specified edits to existing tests**
        >
        > **What we do NOT consider Good First Issues:**
        >
        > - Writing new documentation, examples, or tests from scratch
        > - Any task requiring design or architectural decisions
        > - Changes to SDK behavior, public APIs, or contracts
        > - Protocol, protobuf, or DLT logic changes
        > - Work spanning multiple files or subsystems
        > - Tasks requiring deep domain or protocol knowledge
        >
        > 📖 For details, see:  
        > `docs/maintainers/good_first_issue_candidate_guidelines.md`

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the Issue
      description: |
        Describe the issue in a way that is understandable to new contributors.
        Do NOT assume knowledge of the codebase, Hiero, or distributed ledgers.
        Link to relevant code or documentation where helpful.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ## 👾 Description of the Issue — Example (C++)

        The example for `TokenAssociateTransaction` located in:

        ```
        src/sdk/main/src/TokenAssociateTransaction.cc
        ```

        correctly implements token association logic. However, the method
        `initFromSourceTransactionBody()` currently performs multiple responsibilities:
        - Validating the transaction body
        - Extracting the account ID
        - Extracting token IDs

        Because all logic is implemented inline, the method is harder to read
        and understand for new contributors.

        The behavior is correct, but the structure can be improved for clarity
        without changing functionality.

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        Describe what needs to be done at a high level.
        The solution must be fully specified and require no design decisions.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ## 💡 Proposed Solution — Example (C++)

        Refactor `initFromSourceTransactionBody()` by extracting
        clearly named private helper methods.

        The refactor must:
        - Preserve existing behavior
        - Avoid public API changes
        - Be confined to `TokenAssociateTransaction.cc`

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: |
        Describe the concrete technical steps needed to solve the issue.
        Break them down into small, easy-to-follow steps.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ### 👩‍💻 Implementation — Example (C++)

        To refactor `initFromSourceTransactionBody()`:

        - [ ] Identify logic that validates the transaction body
        - [ ] Extract account ID parsing into a helper method
        - [ ] Extract token ID parsing into a helper method
        - [ ] Call helper methods from `initFromSourceTransactionBody()`
        - [ ] Ensure no behavior changes occur
        - [ ] Build the SDK and run existing tests

        Example helper method signatures:

        ```cpp
        void extractAccountId(const proto::TokenAssociateTransactionBody& body);
        void extractTokenIds(const proto::TokenAssociateTransactionBody& body);
        ```

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Checklist required to merge a pull request
      value: |
        To merge a pull request for this issue:

        - [ ] **Assignment:** Comment `/assign`
        - [ ] **Scope:** Changes are limited to the files described above
        - [ ] **Behavior:** No SDK behavior or API changes
        - [ ] **Signed Commits:** DCO and GPG signed  
              docs/sdk_developers/signing.md
        - [ ] **Tests:** All CI checks pass
        - [ ] **Review:** All review feedback addressed
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-Step Contribution Guide
      description: Contribution workflow for new contributors
      value: |
        If this is your first open-source contribution, follow these steps:

        - [ ] Comment `/assign` to request the issue
        - [ ] Fork the repository and create a branch
        - [ ] Make the requested changes
        - [ ] Sign each commit using `-s -S`
        - [ ] Push your branch and open a pull request

        Helpful resources:
        - Contributing Guide: CONTRIBUTING.md
        - Workflow Training: docs/sdk_developers/training/workflow
        - Signing Guide: docs/sdk_developers/signing.md

        ❗ Pull requests cannot be merged without signed commits.
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Information
      description: Extra context or resources for contributors
      value: |

        Join our community on Discord:
        https://discord.com/channels/905194001349627914/1337424839761465364

        If you have questions, feel free to ask in the comments — maintainers are happy to help!
