name: Beginner Issue Template
description: Create a Beginner Issue for fairly new contributors (C++)
title: "[Beginner]: "
labels: ["beginner"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort. If this is your first open-source contribution, welcome!

        This template is designed to help you create a **Beginner-friendly issue**:
        a moderately easy, well-scoped task that helps contributors build confidence
        and deepen their understanding of the **Hiero C++ SDK** codebase.

        ---

  - type: textarea
    id: intro
    attributes:
      label: 🐥 Beginner Friendly
      description: Who is this issue for?
      value: |
        This issue is intended for contributors who have already completed at least
        one **Good First Issue** in the Hiero project and are now ready for slightly
        more independent work.

        Beginner Issues may require reading existing C++ code, understanding how
        components interact, and making small design-consistent changes — but they
        remain well-scoped and approachable.

        The goal is to help you grow your skills while continuing to contribute safely.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 🐥 Beginner Issue Guidelines
        >
        > Beginner Issues are for contributors who are comfortable with the basic
        > project workflow and have **some C++ experience**.
        >
        > These issues may require:
        > - Light investigation
        > - Reading and understanding existing code
        > - Applying established patterns
        >
        > **What we generally consider Beginner Issues:**
        >
        > - **Small, well-scoped updates to existing tests**
        >   - Extending an existing test with additional assertions
        > - **Narrow improvements to `src` functionality**, such as:
        >   - Improving method implementations
        >   - Adding or refining helper functions
        >   - Improving const-correctness or readability
        > - **Documentation improvements**
        >   - Improving Doxygen comments
        >   - Clarifying example code
        > - **Enhancements to existing examples**
        >   - Adding clearly defined additional steps or variants
        >
        > **What we generally do NOT consider Beginner Issues:**
        >
        > - Tasks better suited for Good First Issues (purely mechanical changes)
        > - Writing entirely new examples or test suites
        > - Changes to SDK behavior, public APIs, or contracts
        > - Changes to DLT, protobuf, or serialization logic
        > - Work requiring deep knowledge across multiple subsystems
        >
        > 📖 For more details, see:  
        > `docs/maintainers/beginner_issue_guidelines.md`

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the Issue
      description: |
        Describe the issue in a way that is approachable to beginner contributors.
        Assume only basic familiarity with C++, the repository structure, and Hiero.
        Encourage learning and exploration, but keep the task clearly defined.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ## 👾 Description of the Issue — Example (C++)

        The `AccountId` class located in:

        ```
        src/sdk/main/include/hiero/account/AccountId.h
        src/sdk/main/src/account/AccountId.cc
        ```

        currently provides a `toString()` method, but when `AccountId` objects are
        logged or inspected during debugging, the output is not very descriptive.

        Improving the readability of this output would make debugging and logging
        easier for developers using the SDK.

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        Describe what needs to be done to solve the issue.
        The solution should be clear, well-scoped, and not require architectural decisions.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ## 💡 Proposed Solution — Example (C++)

        Improve the string representation of `AccountId` by refining the existing
        `toString()` method (or related helper methods) to clearly show the shard,
        realm, and account number.

        The change must:
        - Preserve existing behavior
        - Avoid public API changes
        - Be consistent with patterns used by other ID classes

        Example output:

        ```
        AccountId{shard=0, realm=0, num=1234}
        ```

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: |
        Describe the technical steps required to implement the solution.
        Break them into small, easy-to-follow steps.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ### 👩‍💻 Implementation — Example (C++)

        To implement this improvement:

        - [ ] Locate the `AccountId` class in the `src/` directory
        - [ ] Review the existing `toString()` implementation
        - [ ] Identify how other ID classes format their string output
        - [ ] Update the implementation to:
        > - Clearly display `shard`, `realm`, and `num`
        > - Use a consistent, readable format
        - [ ] Update or extend existing unit tests to validate the new output
        - [ ] Build the SDK and ensure all tests pass

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Checklist required to merge a pull request
      value: |
        To merge a pull request for this issue:

        - [ ] **Assignment:** Comment `/assign`  
              docs/sdk_developers/training/workflow/04_assigning_issues.md
        - [ ] **Scope:** Changes are limited to the files described
        - [ ] **Behavior:** No changes to SDK behavior or public APIs
        - [ ] **Changelog Entry:** Added  
              docs/sdk_developers/changelog_entry.md
        - [ ] **Signed Commits:** DCO and GPG signed  
              docs/sdk_developers/signing.md
        - [ ] **Tests:** All CI checks pass
        - [ ] **Review:** All feedback addressed
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-Step Contribution Guide
      description: Contribution workflow for beginner contributors
      value: |
        - [ ] Comment `/assign` to request the issue
        - [ ] Fork the repository and create a branch
        - [ ] Make the requested changes
        - [ ] Sign each commit using `-s -S`
        - [ ] Add a changelog entry
        - [ ] Push your branch and open a pull request

        Helpful resources:
        - CONTRIBUTING.md
        - docs/sdk_developers/training/workflow
        - docs/sdk_developers/signing.md

        ❗ Pull requests cannot be merged without signed commits and a changelog entry.
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Information
      description: Extra resources or context for contributors
      value: |
        Helpful resources:
        - SDK Developer Docs:
          https://github.com/hiero-ledger/hiero-sdk-cpp/tree/main/docs/sdk_developers
        - SDK Developer Training:
          https://github.com/hiero-ledger/hiero-sdk-cpp/tree/main/docs/sdk_developers/training

        Join the community on Discord:
        https://github.com/hiero-ledger/hiero-sdk-cpp/blob/main/docs/discord.md

        If you get stuck or have questions, feel free to ask in the issue comments —
        maintainers are happy to help!
