name: Intermediate Issue Template
description: Create a well-documented issue for contributors with some familiarity with the codebase (C++)
title: "[Intermediate]: "
labels: ["intermediate"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort.

        This template is designed to help you create an **Intermediate-level issue**
        for contributors who already have some familiarity with the **Hiero C++ SDK**
        codebase and contribution workflow.

        The goal is to create an issue for contributors who:
        - have basic familiarity with the Hiero C++ SDK codebase
        - have experience following our contribution workflow
        - are confident navigating existing source code, examples, and tests
        ---

  - type: textarea
    id: intro
    attributes:
      label: 🧩 Intermediate Contributors
      description: Who is this issue for?
      value: |
        This issue is intended for contributors who already have some familiarity with the
        Hiero C++ SDK codebase and contribution workflow.

        You should feel comfortable:
        - navigating `src/`, `examples/`, and `tests/`
        - understanding existing SDK abstractions and patterns
        - following the standard PR workflow without additional onboarding

        If this is your first contribution to the project, we recommend starting with a
        **Good First Issue** or **Beginner Issue** before working on this one.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 🧭 What we consider an *Intermediate Issue*
        >
        > This issue generally:
        >
        > - Requires **some knowledge of the existing C++ codebase**, but not deep architectural expertise
        > - Is **narrowly scoped** and well-contained
        > - Is **low to medium risk**, avoiding highly sensitive DLT or consensus logic
        > - May involve **small feature additions or meaningful refactors**
        > - Provides **sufficient context and references** to reason about a solution
        > - Often has **similar patterns elsewhere in the codebase**
        >
        > **What this issue is NOT:**
        > - A beginner-friendly onboarding task
        > - A large architectural redesign
        > - A change requiring extensive cross-module refactors
        > - A breaking public API change

  - type: textarea
    id: problem
    attributes:
      label: 🐞 Problem Description
      description: |
        Describe the problem clearly and precisely.

        You may assume the reader:
        - understands the SDK structure
        - can navigate `src/`, `examples/`, and `tests/`
        - is comfortable reading existing C++ implementations

        Still explain:
        - what is wrong or missing
        - where it lives in the codebase
        - why it matters
      value: |
        Describe the problem here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for Problem (hidden in submission) -->
        ## 🐞 Problem – Example (C++)

        The `TransactionReceiptQuery` implementation in the C++ SDK currently exposes
        only the parent transaction receipt, even when child receipts are available.

        In particular:
        - The SDK does not provide a way to opt in to retrieving child receipts
        - The mirror node API supports returning child receipts
        - Similar query types in the SDK already support optional configuration flags

        This limitation makes it difficult to inspect scheduled or child transactions
        without performing additional manual queries.

        Relevant files:
        - `src/sdk/main/include/hiero/query/TransactionReceiptQuery.h`
        - `src/sdk/main/src/query/TransactionReceiptQuery.cc`
        - `examples/query/transaction_receipt_query.cc`

  - type: textarea
    id: solution
    attributes:
      label: 💡 Expected Solution
      description: |
        Describe the intended outcome.

        This does NOT need to be a full implementation plan,
        but should explain:
        - what should change
        - what should NOT change
        - any constraints or boundaries
      value: |
        Describe the expected solution here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for Solution (hidden in submission) -->
        ## 💡 Expected Solution – Example (C++)

        Introduce an optional configuration flag on `TransactionReceiptQuery`
        that allows callers to explicitly request child receipts.

        The change should:
        - Be opt-in (default behavior must remain unchanged)
        - Reuse existing receipt parsing logic where possible
        - Avoid introducing breaking API changes
        - Follow existing query configuration patterns

        Example usage:

        ```cpp
        TransactionReceipt receipt =
          TransactionReceiptQuery()
            .setTransactionId(transactionId)
            .setIncludeChildren(true)
            .execute(client);
        ```

  - type: textarea
    id: implementation
    attributes:
      label: 🧠 Implementation Notes
      description: |
        Provide technical guidance to help implementation.

        Examples:
        - files or modules likely involved
        - patterns already used elsewhere
        - things to be careful about
        - known edge cases
      value: |
        Add implementation notes here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <!-- Example for Implementation Notes (hidden in submission) -->
        ## 🧠 Implementation Notes – Example (C++)

        Likely steps:

        - Add an optional boolean member (e.g. `mIncludeChildren`) to
          `TransactionReceiptQuery`
        - Ensure the flag is propagated to the mirror node request
        - Update response parsing to include child receipts when present
        - Update or extend the example in:
          `examples/query/transaction_receipt_query.cc`
        - Add or update unit tests covering both default and opt-in behavior

        Similar patterns can be found in other query classes that support
        optional response extensions.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Define what "done" means for this issue
      value: |
        To merge this issue, the pull request must:

        - [ ] Fully address the problem described above
        - [ ] Follow existing project conventions and C++ patterns
        - [ ] Avoid breaking public APIs
        - [ ] Include tests and/or example updates where appropriate
        - [ ] Pass all CI checks
        - [ ] Use DCO and GPG-signed commits
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 📚 Additional Context or Resources
      description: |
        Add any links, references, or extra notes that may help.
      value: |
        Join the community on Discord:
        https://discord.com/channels/905194001349627914/1337424839761465364
    validations:
      required: false
