name: Intermediate Issue Template
description: Create a well-documented issue for contributors with some familiarity with the codebase (C++)
title: "[Intermediate]: "
labels: ["intermediate"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 😊

        We truly appreciate your time and effort.

        This template is here to help you create an **Intermediate-level issue** for
        contributors who are comfortable with the basics and ready to take on a bit
        more ownership in the **Hiero C++ SDK** codebase.

        These issues usually involve a mix of exploration, reasoning, and implementation,
        while still having clear goals and boundaries.

        > Maintainers can read more about:
        > [Intermediate Issues](https://github.com/hiero-ledger/hiero-sdk-cpp/blob/main/docs/maintainers/guidelines-intermediate-issues.md)
        ---

  - type: textarea
    id: intro
    attributes:
      label: 🧩 Intermediate Friendly
      description: Who is this issue for?
      value: |
        This issue is a good fit for contributors who are already familiar with the
        Hiero C++ SDK and feel comfortable navigating the codebase.

        Intermediate Issues often involve:
        - Exploring existing implementations  
        - Understanding how different components work together  
        - Making thoughtful changes that follow established patterns  

        The goal is to support deeper problem-solving while keeping the task clear,
        focused, and enjoyable to work on.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 🧭 About Intermediate Issues
        >
        > Intermediate Issues are a great next step for contributors who enjoy
        > digging into the codebase and reasoning about how things work.
        >
        > These issues often:
        > - Involve multiple related files or components  
        > - Encourage investigation and understanding of existing behavior  
        > - Leave room for thoughtful implementation choices  
        > - Stay focused on a clearly defined goal  
        >
        > Other kinds of contributions — from beginner-friendly tasks to large
        > system-level changes — are just as valuable and use different labels.

  - type: textarea
    id: problem
    attributes:
      label: 🐞 Problem Description
      description: |
        Describe the problem clearly and precisely.

        Try to explain:
        - What is missing, unclear, or not working as expected  
        - Where it lives in the codebase  
        - Why it matters to users or contributors  
      value: |
        Describe the problem here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ## 🐞 Problem – Example (C++)

        The `TransactionReceiptQuery` implementation currently returns only the
        parent transaction receipt, even when child receipts are available.

        The mirror node API supports returning child receipts, and similar query
        types in the SDK already support optional configuration flags.

        This makes it harder to inspect scheduled or child transactions without
        performing additional manual queries.

        Relevant files:
        - `src/sdk/main/include/hiero/query/TransactionReceiptQuery.h`
        - `src/sdk/main/src/query/TransactionReceiptQuery.cc`
        - `examples/query/transaction_receipt_query.cc`

  - type: textarea
    id: solution
    attributes:
      label: 💡 Expected Outcome
      description: |
        Describe what a good solution would look like.

        You don’t need to provide a full implementation plan, but it helps to explain:
        - What should change  
        - What should stay the same  
        - Any important constraints or goals  
      value: |
        Describe the expected outcome here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ## 💡 Expected Outcome – Example (C++)

        Add an optional configuration flag to `TransactionReceiptQuery` that allows
        callers to request child receipts.

        The change should:
        - Be opt-in (default behavior stays the same)  
        - Reuse existing receipt parsing logic  
        - Follow existing query configuration patterns  
        - Aim to avoid breaking public APIs  

        Example usage:

        ```cpp
        TransactionReceipt receipt =
          TransactionReceiptQuery()
            .setTransactionId(transactionId)
            .setIncludeChildren(true)
            .execute(client);
        ```

  - type: textarea
    id: implementation
    attributes:
      label: 🧠 Implementation Notes
      description: |
        Share helpful technical context to guide implementation.

        For example:
        - Which files or modules are likely involved  
        - Similar patterns elsewhere in the codebase  
        - Things to be careful about  
        - Known edge cases or constraints  
      value: |
        Add implementation notes here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <!-- Example (hidden in submission) -->
        ## 🧠 Implementation Notes – Example (C++)

        Likely steps:

        - Add an optional boolean member (e.g. `mIncludeChildren`) to
          `TransactionReceiptQuery`
        - Propagate the flag to the mirror node request
        - Update response parsing to include child receipts
        - Update the example in:
          `examples/query/transaction_receipt_query.cc`
        - Add or adjust unit tests for both default and opt-in behavior

        Similar patterns can be found in other query classes with optional flags.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Define what “done” looks like for this issue
      value: |
        To help get this change merged smoothly:

        - [ ] Address the problem described above  
        - [ ] Follow existing project conventions  
        - [ ] Avoid breaking public APIs  
        - [ ] Include tests and/or example updates where appropriate  
        - [ ] Pass all CI checks  
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Contribution Guide
      description: Contribution workflow for intermediate contributors
      value: |
        To help your contribution go as smoothly as possible, we recommend following these steps:

        - [ ] Comment `/assign` to request the issue
        - [ ] Wait for assignment
        - [ ] Fork the repository and create a branch
        - [ ] Make the requested changes
        - [ ] Sign each commit using `-s -S`
        - [ ] Push your branch and open a pull request

        Read [Workflow Guide](docs/training/workflow.md) for step-by-step workflow guidance.
        Read [README.md](README.md) for setup instructions.

        ❗ Pull requests **cannot be merged** without `S` and `s` signed commits. Read [Signing Guide](docs/training/signing.md).
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 📚 Additional Context or Resources
      description: |
        Add any links, references, or extra notes that may help.
      value: |
        If you have questions, the community is happy to help:

        https://discord.com/channels/905194001349627914/1337424839761465364
    validations:
      required: false

