name: Advanced Issue Template
description: Create a high-impact issue for experienced contributors with deep familiarity with the codebase (C++)
title: "[Advanced]: "
labels: ["advanced"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for contributing!** 🚀

        We truly appreciate your interest in tackling an **Advanced issue**.

        This template is designed for work that requires **deep familiarity with the Hiero C++ SDK**
        and confidence making changes that may span multiple modules or affect core behavior.

        The goal is to create issues for contributors who:
        - have strong familiarity with the Hiero C++ SDK internals
        - are comfortable reasoning about trade-offs and design decisions
        - can work independently with minimal guidance
        ---

  - type: textarea
    id: intro
    attributes:
      label: 🧠 Advanced Contributors
      description: Who is this issue intended for?
      value: |
        This issue is intended for contributors who are already very familiar with the
        Hiero C++ SDK codebase and its architectural patterns.

        You should feel comfortable:
        - navigating multiple modules across `src/`
        - understanding and modifying core SDK abstractions
        - reasoning about API design and backwards compatibility
        - updating or extending tests, examples, and documentation as needed
        - making changes that may affect public-facing behavior

        New contributors should start with **Good First Issues**,
        **Beginner Issues**, or **Intermediate Issues** first.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!WARNING]
        > ### 🧭 What we consider an *Advanced Issue*
        >
        > This issue typically:
        >
        > - Requires **deep understanding of existing C++ SDK design and behavior**
        > - May touch **core abstractions**, shared utilities, or cross-cutting concerns
        > - May involve **non-trivial refactors**, design changes, or behavior extensions
        > - Has **medium to high risk** if implemented incorrectly
        > - Requires careful consideration of **backwards compatibility**
        > - Often requires updating **tests, examples, and documentation together**
        >
        > **What this issue is NOT:**
        > - A simple bug fix
        > - A narrowly scoped refactor
        > - A task solvable by following existing patterns alone
        >
        > 📖 Helpful references:
        > - `docs/sdk_developers/training`
        > - `docs/sdk_developers/training/setup/project_structure.md`
        > - `docs/sdk_developers/rebasing.md`

  - type: textarea
    id: problem
    attributes:
      label: 🐞 Problem Description
      description: |
        Describe the problem in depth.

        You may assume the reader:
        - understands the overall SDK architecture
        - can navigate and reason about multiple modules
        - is comfortable reading and modifying core C++ logic

        Clearly explain:
        - what the current behavior is
        - why it is insufficient or incorrect
        - which components or layers are involved
        - any relevant historical or design context
      value: |
        Describe the problem here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for Problem (hidden in submission) -->
        ## 🐞 Problem – Example (C++)

        The current transaction execution flow in the C++ SDK tightly couples
        transaction submission, receipt polling, record retrieval, and retry logic
        into a single execution path.

        This coupling makes it difficult to:
        - customize retry behavior
        - extend execution semantics for scheduled transactions
        - introduce mirror-node-backed execution strategies
        - test individual execution stages in isolation

        Several planned SDK enhancements would benefit from a clearer
        separation of concerns in this area.

        Relevant areas:
        - `src/sdk/main/src/transaction/`
        - `src/sdk/main/src/execution/`
        - `src/sdk/main/src/client/`

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed / Expected Solution
      description: |
        Describe the intended direction or design.

        This should include:
        - the high-level approach
        - any new abstractions or changes to existing ones
        - constraints (e.g. backwards compatibility, performance, API stability)
        - known alternatives and why they were rejected (if applicable)

        A full design document is not required, but the reasoning and intent
        should be clear.
      value: |
        Describe the proposed solution here.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for Solution (hidden in submission) -->
        ## 💡 Proposed Solution – Example (C++)

        Introduce a dedicated **transaction execution pipeline** abstraction
        that separates the following concerns:

        - transaction submission
        - receipt polling
        - record retrieval
        - retry and timeout logic

        The new design should:
        - preserve existing public APIs
        - allow advanced users to override or extend execution behavior
        - make individual execution stages independently testable

        Existing transaction execution logic should be refactored
        to use the new pipeline internally.

  - type: textarea
    id: implementation
    attributes:
      label: 🧠 Implementation & Design Notes
      description: |
        Provide detailed technical guidance.

        This section is especially important for Advanced issues.

        Consider including:
        - specific modules or classes involved
        - suggested refactoring strategy
        - migration or deprecation concerns
        - testing strategy
        - performance, concurrency, or security considerations
      value: |
        Add detailed implementation notes here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <!-- Example for Implementation Notes (hidden in submission) -->
        ## 🧠 Implementation Notes – Example (C++)

        Suggested approach:

        - Introduce a new `ExecutionPipeline` abstraction under:
          `src/sdk/main/src/execution/`
        - Refactor existing transaction execution code to delegate
          to this pipeline
        - Preserve existing public APIs and default behavior
        - Add focused unit tests for each pipeline stage
        - Update at least one example to demonstrate extensibility

        Care must be taken to preserve timeout semantics and retry behavior
        relied upon by existing SDK users.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Define what "done" means for this issue
      value: |
        To merge this issue, the pull request must:

        - [ ] Fully address the problem and design goals described above
        - [ ] Maintain backwards compatibility unless explicitly approved otherwise
        - [ ] Follow existing architectural and C++ coding conventions
        - [ ] Include comprehensive tests covering new and existing behavior
        - [ ] Update relevant examples and documentation
        - [ ] Pass all CI checks
        - [ ] Use DCO and GPG-signed commits
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 📚 Additional Context, Links, or Prior Art
      description: |
        Add any references that may help:
        - design documents
        - prior discussions
        - related issues or pull requests
        - external references
      value: |
        Optional.
    validations:
      required: false
