name: Good First Issue Candidate (C++)
description: Propose a potential Good First Issue (candidate) for the Hiero C++ SDK
title: "[Good First Issue Candidate][C++]:"
labels: ["Good First Issue Candidate", "C++"]
assignees: []
body:
  - type: textarea
    id: intro-gfi-candidate
    attributes:
      label: ⚠️ Good First Issue — Candidate
      value: |
        > This issue is **not yet a confirmed Good First Issue**.
        > It is being evaluated for suitability and may require
        > clarification or refinement before it is ready to be picked up.
        >
        > Please wait for maintainer confirmation before starting work.
        >
        > Maintainers can read more about Good First Issues:
        > docs/maintainers/good_first_issue_candidate_guidelines.md
    validations:
      required: false

  - type: textarea
    id: intro
    attributes:
      label: 🆕🐥 First Timers Only
      description: Who is this issue for?
      value: |
        This issue is intended for contributors who are new or have made minimal contributions to the **Hiero C++ SDK**.

        Creating a pull request (PR) can be a major barrier for new contributors.
        Issues labeled as **Good First Issue** are designed to help you learn the
        codebase, tooling, and contribution workflow while making a meaningful improvement.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### 📋 Good First Issue Candidate Guidelines (C++)
        >
        > **What we generally consider good first issue candidates:**
        > - Narrow refactors in existing C++ code
        > - Improving readability or separation of concerns
        > - Const-correctness and type safety
        > - Small documentation improvements (Doxygen, inline comments)
        > - Targeted additions to existing tests
        >
        > **What we generally do NOT consider good first issue candidates:**
        > - New core features
        > - New transaction types
        > - Large architectural changes
        > - Changes requiring deep knowledge of multiple subsystems

  - type: textarea
    id: issue
    attributes:
      label: 👾 Description of the issue
      description: |
        Describe the issue in a way that is understandable to new contributors.
        Do not assume prior knowledge of the codebase or Hiero.
        Add links to relevant code or documentation where possible.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for problem (hidden in submission) -->
        ## 👾 Description of the issue — Example (C++)

        The C++ implementation of `TokenAssociateTransaction` currently combines
        protobuf parsing, validation, and object construction in a single method,
        making it difficult for new contributors to follow.

        ```cpp
        void TokenAssociateTransaction::initFromSourceTransactionBody()
        {
          const proto::TransactionBody transactionBody = getSourceTransactionBody();

          if (!transactionBody.has_tokenassociate())
          {
            throw std::invalid_argument("Transaction body doesn't contain TokenAssociate data");
          }

          const proto::TokenAssociateTransactionBody& body = transactionBody.tokenassociate();

          if (body.has_account())
          {
            mAccountId = AccountId::fromProtobuf(body.account());
          }

          for (int i = 0; i < body.tokens_size(); ++i)
          {
            mTokenIds.push_back(TokenId::fromProtobuf(body.tokens(i)));
          }
        }
        ```

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the approach to solving the issue.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for the solution (hidden in submission) -->
        ## 💡 Solution — Example (C++)

        Refactor the transaction implementation by extracting protobuf parsing
        into clearly named helper functions while keeping external behavior unchanged.

  - type: textarea
    id: implementation
    attributes:
      label: 👩‍💻 Implementation Steps
      description: Break down the technical steps required to solve the issue.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example implementation (hidden in submission) -->
        ### 👩‍💻 Implementation — Example (C++)

        - [ ] Identify parsing logic in `TokenAssociateTransaction`
        - [ ] Extract parsing into helper methods
        - [ ] Ensure existing tests pass
        - [ ] Update documentation if needed

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      value: |
        - [ ] All commits are DCO and GPG signed
        - [ ] All tests pass
        - [ ] The issue is fully addressed
        - [ ] Code review feedback has been resolved
    validations:
      required: true
